/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ACMP0.h
**     Project     : IrDA
**     Processor   : MKE06Z128VLK4
**     Component   : Init_ACMP
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-05-31, 23:50, # CodeGen: 6
**     Abstract    :
**          This file implements the ACMP (ACMP0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : ACMP0
**          Device                                         : ACMP0
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Hystersis selection                          : 20 mV
**            DAC module                                   : Initialize
**              DAC device                                 : DAC6b0
**              Reference selection                        : Internal
**              Output level selection                     : 1
**              Module enable                              : yes
**          Pins/Signals                                   : 
**            Input pins                                   : 
**              Input pin 0                                : Enabled
**                Input pin 0                              : PTA0/KBI0_P0/FTM0_CH0/I2C0_4WSCLOUT/ACMP0_IN0/ADC0_SE0
**              Input pin 1                                : Disabled
**              Input pin 2                                : Disabled
**              Input pin 3                                : Enabled
**                Input pin 3                              : <Automatic>
**            Output pin                                   : Disabled
**          Interrupts                                     : 
**            Interrupt                                    : INT_ACMP0
**            Interrupt request                            : <Automatic>
**            Interrupt priority                           : <Automatic>
**            ISR name                                     : 
**            Compare interrupt                            : Disabled
**            Edge type                                    : Falling
**          Initialization                                 : 
**            Comparator module                            : Enabled
**            Initial positive input                       : Pin 0
**            Initial negative input                       : Pin 3
**            Call Init method                             : yes
**            Utilize after reset values                   : yes
**     Contents    :
**         Init - void ACMP0_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file ACMP0.h
** @version 01.00
** @brief
**          This file implements the ACMP (ACMP0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup ACMP0_module ACMP0 module documentation
**  @{
*/         

#ifndef ACMP0_H_
#define ACMP0_H_

/* MODULE ACMP0. */

#include "ACMP0_Init.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initialization method user name */
#define ACMP0_Init ACMP0_Init
/* PDD macros peripheral base address parameter */
#define ACMP0_DEVICE ACMP0_BASE_PTR

#ifdef __cplusplus
}
#endif

/* END ACMP0. */
#endif /* #ifndef __ACMP0_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/


